# Use Node.js as the base image
FROM node:18.17.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files to the container
COPY package.json package-lock.json ./

# Copy the Next.js project into the container
COPY . ./

# Install dependencies
RUN npm install

# Build the Next.js application
RUN npm run build

# Expose the port Next.js runs on
EXPOSE 3002

# Command to run Next.js application
CMD ["npm", "start"]